### ISSUE TITLE
moving from karma to grunt-tdd

### ISSUE THREAD

**Issue by revdave33** [christianalfoni/grunt-tdd#2]
I really like the look of grunt-tdd and am trying to convert the karma setup from the meanjs boilerplate. I have the node version of grunt-tdd working with mocha. I'm running into trouble getting the browser part with angularjs set up using jasmine. It doesn't look like it wants to setup jasmine correctly.

using grunt tdd:browser --runAll it get this error:
Running "tdd:browser" (tdd) task

phantom stderr: execvp(): No such file or directory

Fatal error: Cannot call method 'createPage' of undefined

When I run it without --runAll the browser shows a lot of errors related to the boilerplate I'm using trying to set up some custom matchers using jasmine.addMatcher. It doesn't recognize the command.

In the grunt config block I duplicated the lib list of files from the karma config file that is working with jasmine.

not sure how to approach debugging this.

**Comment by christianalfoni** [comment]
Hi David!

Thanks for your feedback on grunt-tdd :-)

It would help a lot to see the project structure and the content of the Gruntfile. Would it be possible to wrap it up and send it on christianalfoni@gmail.com? (without node_modules folder)

Thanks and have a nice day!

Christian

**Comment by revdave33** [comment]
The project is on github. In my repository my-meanjs under the branch grunt-tdd.

The only two files I've changed from the original is the package.json and the gruntfile.js.

Thanks, David

**Comment by christianalfoni** [comment]
Hi again David,

I have taken a look at the project. It looks really awesome :-)

I have gone through the config and identified the issues:

The three “files” properties of the configuration does the following:

Libs: Loads any files defined at the very beginning of the test HTML runner file
Sources: Loads after the libs are loaded
Tests: Loads after the sources and actual reporter is added to the HTML runner file

I see the project is very dependant on order of loading files, which is why you have the “modulesJSFiles” at the top of the Gruntfile I suppose. I have built a module loader that lets you load files without worrying about load order, which is in revised version here: https://github.com/MarcelloSystems/module-loader-tdd. It is like a “sister”-lib to grunt-tdd. Just an input, it is absolutely not needed though :-)

So, back to  issue here
1.  I changed the regexp to traverse file, made sure the the spec files are not included. Line 6 in Gruntfile.js now looks like this:

var modulesJSFiles = utilities.walk('./public/modules', /^(?!._spec.js)._.js.*$/);
1. I also changed how files were loaded a bit, to this, on line 119:
   
   ```
               sources: [
                   'public/js/config.js’, // I understand that config.js and application.js has to be loaded first
                   'public/js/application.js’
   
               ].concat(modulesJSFiles), // Load the rest of the modules
               libs: [
   ```
   
   'public/lib/angular/angular.js',
   'public/lib/angular-animate/angular-animate.js',
   'public/lib/angular-mocks/angular-mocks.js',
   'public/lib/angular-cookies/angular-cookies.js',
   'public/lib/angular-resource/angular-resource.js',
   'public/lib/angular-bootstrap/ui-bootstrap.js',
   'public/lib/angular-ui-utils/ui-utils.js',
   'public/lib/angular-ui-router/release/angular-ui-router.js'
                   ], // Removed loading of modules here, as they are part of source files and should be loaded above
                   tests: ['public/*_/_spec.js'] // Did not change this I believe :-)
2. Now you do get an error on articles.spec.js, the reason for that is that grunt-tdd is running the latest 1.x version of Jasmine, not 2.0, and the reason for that is that the tests needs to run in Node also, which is not supported yet on Jasmine 2.0. Correct me if I am wrong here. It would be possible to run 2.0 on browser tests and 1.x on Node tests though, what do you think?

Okay, doing these changes now runs the tests successfully except the addMatcher thingy. Please let me know if you have any more questions, want to look into module-loader-tdd etc. And thank you very much for your feedback!

Best regards
Christian

**Comment by christianalfoni** [comment]
Btw, sorry about not answering the original --runAll question. I was a bit quick here. There is definitely something wrong with createPage method. It does not trigger the callback at all. Hm, maybe there is an issue with new version of phantomjs.

I will have to look more into that. Let you know!

Christian

From: Christian Jørgensen <christian.jorgensen@marcello.no<mailto:christian.jorgensen@marcello.no>>
Date: Saturday 5 April 2014 21:10
To: christianalfoni/grunt-tdd <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: Re: [grunt-tdd] moving from karma to grunt-tdd (#2)

Hi again David,

I have taken a look at the project. It looks really awesome :-)

I have gone through the config and identified the issues:

The three “files” properties of the configuration does the following:

Libs: Loads any files defined at the very beginning of the test HTML runner file
Sources: Loads after the libs are loaded
Tests: Loads after the sources and actual reporter is added to the HTML runner file

I see the project is very dependant on order of loading files, which is why you have the “modulesJSFiles” at the top of the Gruntfile I suppose. I have built a module loader that lets you load files without worrying about load order, which is in revised version here: https://github.com/MarcelloSystems/module-loader-tdd. It is like a “sister”-lib to grunt-tdd. Just an input, it is absolutely not needed though :-)

So, back to  issue here
1.  I changed the regexp to traverse file, made sure the the spec files are not included. Line 6 in Gruntfile.js now looks like this:

var modulesJSFiles = utilities.walk('./public/modules', /^(?!._spec.js)._.js.*$/);
1. I also changed how files were loaded a bit, to this, on line 119:
   
   ```
               sources: [
                   'public/js/config.js’, // I understand that config.js and application.js has to be loaded first
                   'public/js/application.js’
   
               ].concat(modulesJSFiles), // Load the rest of the modules
               libs: [
   ```
   
   'public/lib/angular/angular.js',
   'public/lib/angular-animate/angular-animate.js',
   'public/lib/angular-mocks/angular-mocks.js',
   'public/lib/angular-cookies/angular-cookies.js',
   'public/lib/angular-resource/angular-resource.js',
   'public/lib/angular-bootstrap/ui-bootstrap.js',
   'public/lib/angular-ui-utils/ui-utils.js',
   'public/lib/angular-ui-router/release/angular-ui-router.js'
                   ], // Removed loading of modules here, as they are part of source files and should be loaded above
                   tests: ['public/*_/_spec.js'] // Did not change this I believe :-)
2. Now you do get an error on articles.spec.js, the reason for that is that grunt-tdd is running the latest 1.x version of Jasmine, not 2.0, and the reason for that is that the tests needs to run in Node also, which is not supported yet on Jasmine 2.0. Correct me if I am wrong here. It would be possible to run 2.0 on browser tests and 1.x on Node tests though, what do you think?

Okay, doing these changes now runs the tests successfully except the addMatcher thingy. Please let me know if you have any more questions, want to look into module-loader-tdd etc. And thank you very much for your feedback!

Best regards
Christian

**Comment by revdave33** [comment]
Thanks, Christian,

I can't take any credit for the project, it is a fork of a good meanjs seed project. I'm just trying to hack at it to make it work more easily for me.

I see what you mean about jasmine-node not yet working with jasmine 2.0.0. I was looking at the changelog and wondered if that was a big part of that not working.

Everything is a work in progress. I'll keep this open while you try to figure out what the issue is with phantom-node.

David

**Comment by christianalfoni** [comment]
Hi again David,

I have been looking into this now. I am having trouble figuring out why it has suddenly stopped working. Phantom-node uses socket.IO to communicate between phantomjs and node, and the connection is established, but messages sent to client are not received. I have tried to change socket.IO lib, setting up the communication between client and node differently, but with no success.

To make this work I will have to implement my own phantom js bridge, without socket.IO, just pure websockets or XHR polling. It should not take long though, but I am currently occupied with something else. I should get it in place during next week though :-)

I will let you know!

Christian

**Comment by christianalfoni** [comment]
Ah, finally!

Got it working. Will commit to phantom-node to force XHR polling… at least until phantomjs 2.0 where latest websockets implementation is done.

Hopefully they agree :-)

Christian

**Comment by christianalfoni** [comment]
Allright, have not heard anything from them so forked out and published my own version of node-phantom. By updating to latest version it will use my forked: “node-phantom-xhr” module instead, which works with --runAll

Maybe you have moved on to a different solution by now, but if not, it would be awesome if you could verify the fix :-)

Christian

From: Christian Jørgensen <christian.jorgensen@marcello.no<mailto:christian.jorgensen@marcello.no>>
Date: Sunday 6 April 2014 14:39
To: christianalfoni/grunt-tdd <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: Re: [grunt-tdd] moving from karma to grunt-tdd (#2)

Ah, finally!

Got it working. Will commit to phantom-node to force XHR polling… at least until phantomjs 2.0 where latest websockets implementation is done.

Hopefully they agree :-)

Christian

**Comment by revdave33** [comment]
Still getting this error: 

phantom stderr: execvp(): No such file or directory

Fatal error: Cannot call method 'createPage' of undefined

I do have the latest version. I see it does install your new node-phantomjs-xhr module. Do I need to uninstall the regular node-phantomjs module?

**Comment by christianalfoni** [comment]
Hi again David,

Thanks for the follow up! Is the branch removed? Could not find it on the repo, but got the old one here, so figured out the issue :-)

Here is what I found out:
1.  Grunt is actually verifying the filepaths passed to the sources array. So the paths created by the traverse function at the top does not work:

// Grabbing module files using the walk function
var modulesJSFiles = utilities.walk('./public/modules', /^(?!._spec.js)._.js.*$/);
modulesJSFiles.forEach(function (file, index) {
    modulesJSFiles[index] = modulesJSFiles[index].replace('./', '');
});

The first bold line is the initial change I did to avoid loading spec files as sources, that should still be used

The second bold line is changed and now makes sure that the paths start relatively correct. Earlier it would be: “/public/something”, now it is “public/something”. None of the source files were actually loaded
1. The following change I did last time is still valid and necessary:
   
   ```
               sources: [
                   'public/js/config.js’, // I understand that config.js and application.js has to be loaded first
                   'public/js/application.js’
   
               ].concat(modulesJSFiles), // Load the rest of the modules
               libs: [
   ```
   
   'public/lib/angular/angular.js',
   'public/lib/angular-animate/angular-animate.js',
   'public/lib/angular-mocks/angular-mocks.js',
   'public/lib/angular-cookies/angular-cookies.js',
   'public/lib/angular-resource/angular-resource.js',
   'public/lib/angular-bootstrap/ui-bootstrap.js',
   'public/lib/angular-ui-utils/ui-utils.js',
   'public/lib/angular-ui-router/release/angular-ui-router.js'
                   ], // Removed loading of modules here, as they are part of source files and should be loaded above
                   tests: ['public/*_/_spec.js'] // Did not change this I believe :-)
2. The Articles spec is built for Jasmine 2.0, so please comment out the addMatcher stuff. When done, it should all work

Thanks again for the feedback David!

Christian

**Comment by christianalfoni** [comment]
I pasted the whole Gruntfile.js here, for convenience:

``` javascript
'use strict';

var utilities = require('./config/utilities');

// Grabbing module files using the walk function
var modulesJSFiles = utilities.walk('./public/modules', /^(?!.*spec\.js).*\.js.*$/);
modulesJSFiles.forEach(function (file, index) {
    modulesJSFiles[index] = modulesJSFiles[index].replace('./', '');
});

console.log([
    'public/js/config.js', // I understand that config.js and application.js has to be loaded first
    'public/js/application.js'

].concat(modulesJSFiles));

module.exports = function(grunt) {
    // Project Configuration
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        watch: {
            serverViews: {
                files: ['app/views/**'],
                options: {
                    livereload: true,
                }
            },
            serverJS: {
                files: [
                    'gruntfile.js',
                    'server.js',
                    'config/**/*.js',
                    'app/**/*.js'
                ],
                tasks: ['jshint'],
                options: {
                    livereload: true,
                }
            },
            clientViews: {
                files: ['public/modules/**/views/*.html'],
                options: {
                    livereload: true,
                }
            },
            clientJS: {
                files: [
                    'public/js/**/*.js',
                    'public/modules/**/*.js'
                ],
                tasks: ['jshint'],
                options: {
                    livereload: true,
                }
            },
            clientCSS: {
                files: ['public/**/css/*.css'],
                options: {
                    livereload: true,
                }
            }
        },
        jshint: {
            all: {
                src: [
                    'gruntfile.js',
                    'server.js',
                    'config/**/*.js',
                    'app/**/*.js',
                    'public/js/**/*.js',
                    'public/modules/**/*.js'
                ],
                options: {
                    jshintrc: true
                }
            }
        },
        nodemon: {
            dev: {
                script: 'server.js',
                options: {
                    nodeArgs: ['--debug']
                }
            }
        },
        concurrent: {
            tasks: ['nodemon', 'watch'],
            options: {
                logConcurrentOutput: true
            }
        },
        env: {
            test: {
                NODE_ENV: 'test'
            }
        },
        mochaTest: {
            src: ['app/tests/**/*.js'],
            options: {
                reporter: 'spec',
                require: 'server.js'
            }
        },
        karma: {
            unit: {
                configFile: 'karma.conf.js'
            }
        },
        tdd: {
            // NODE CONFIG
            node: {
                files: {
                    sources: ['app/**/*.js'], // Where your application files are located
                    libs: ['../server.js'], // Any general libs needed to be loaded, will be loaded from your node_modules folder
                    tests: ['app/tests/**/*.js'] // Where your tests are located
                },
                options: {
                    node: true, // Set to true if testing node code
                    runner: 'mocha', // jasmine, mocha or buster
                    expect: false // Use the expect.js library for assertions
                }
            },


            // BROWSER CONFIG
            browser: {
                files: {
                    sources: [
                        'public/js/config.js', // I understand that config.js and application.js has to be loaded first
                        'public/js/application.js'

                    ].concat(modulesJSFiles), // Load the rest of the modules
                    libs: [
                        'public/lib/angular/angular.js',
                        'public/lib/angular-animate/angular-animate.js',
                        'public/lib/angular-mocks/angular-mocks.js',
                        'public/lib/angular-cookies/angular-cookies.js',
                        'public/lib/angular-resource/angular-resource.js',
                        'public/lib/angular-bootstrap/ui-bootstrap.js',
                        'public/lib/angular-ui-utils/ui-utils.js',
                        'public/lib/angular-ui-router/release/angular-ui-router.js'
                    ], // Removed loading of modules here, as they are part of source files and should be loaded above
                    tests: ['public/**/*spec.js'] // Did not change this I believe :-)
                },
                options: {
                    runner: 'jasmine', // jasmine, mocha or buster
                    expect: false, // Use the expect.js library for assertions
                    sinon: false // For spies, stubs and fake XHR
                }
            },
        }
    }
   );

    //Load NPM tasks 
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-jshint');
    grunt.loadNpmTasks('grunt-mocha-test');
    grunt.loadNpmTasks('grunt-karma');
    grunt.loadNpmTasks('grunt-nodemon');
    grunt.loadNpmTasks('grunt-concurrent');
    grunt.loadNpmTasks('grunt-env');
    grunt.loadNpmTasks('grunt-tdd');

    //Making grunt default to force in order not to break the project.
    grunt.option('force', true);

    //Default task(s).
    grunt.registerTask('default', ['jshint', 'concurrent']);

    //Test task.
    grunt.registerTask('test', ['env:test', 'mochaTest', 'karma:unit']);
};
```
